spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /test
    username: test
    password: 123
    listener:
      simple:
        prefetch: 1 # 每次只获取一条消息，处理完才能获取下一个消息
        acknowledge-mode: auto # none，关闭ack；manual，手动ack；auto，自动ack