spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: admin
    password: 12345
  rabbitmq:
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: /

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.entropy.restclient.pojo